### ISSUE TITLE
[Karma][v4.0]The app is freezing  when i click finish to complete  my account. 

### ISSUE THREAD

**Issue by masudr4n4** [YahiaAngelo/Karma#1]
<h4>Actual Behaviour </h4>
The app doing nothing when i click finish to complate my accounts.
<h4>Expected behavior</h4>
Expected that i can finish my account and use that without stacking.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>Click sign up </li>
<li>Give mail,username and password</li>
<li> Click sign up</li>
<li>Now input first name,last name and bio</li>
<li>Click Finish</li>
<li>See the error.</>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v4.0</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/sEqo_5En_yc">https://youtu.be/JjEg0ea4ZF4<

**Comment by maaudrana** [comment]
@YahiaAngelo pls add bug level if this issue is valid tnx.

**Comment by YahiaAngelo** [comment]
> #### Actual Behaviour
> The app doing nothing when i click finish to complate my accounts.
> #### Expected behavior
> Expected that i can finish my account and use that without stacking.
> #### How to reproduce
> 1. Install the apps and open the app
> 2. Click sign up
> 3. Give mail,username and password
> 4. Click sign up
> 5. Now input first name,last name and bio
> 6. Click Finish
> 7. See the error.
> 
> #### Information
> * App version:v4.0
> * OS:Android 9.0
> * Device:Samsung A10
> 
> #### Recording Of The Bug
> [https://youtu.be/JjEg0ea4ZF4<](https://youtu.be/sEqo_5En_yc)

Thanks for reporting.
The issue is : You have to choose a profile picture to pass this step.
And i will try to make it optional.

**Comment by masudr4n4** [comment]
Yeah it will better if it is optional  tnx
