### ISSUE TITLE
App stoped when click on sing out 

### ISSUE THREAD

**Issue by lushohammy** [YahiaAngelo/Karma#3]
#### Expected behavior
After click on sing out the app close smoothly without showing stopped.    

#### Actual behavior
when i click on sing out the app close and shows me stopped. 

#### How to reproduce
* open the app 
* login with email and pass
* then try to sing out
* note the bug

> Browser/App version: 4.0
 Operating system: Android **8.1.0** OPMI

#### Recording Of The Bug
https://youtu.be/rR9wv1JonNA

**Comment by lushohammy** [comment]
@YahiaAngelo please feedback

**Comment by YahiaAngelo** [comment]
[https://github.com/YahiaAngelo/Karma/commit/5ba9a76f5cf22d3440c1969b7d93487618ebb614](url)
