### ISSUE TITLE
App cant remember email and pass while click on remember me

### ISSUE THREAD

**Issue by lushohammy** [YahiaAngelo/Karma#4]
#### Expected behavior
it should be able to remember email and pass when we click on remember me . 

#### Actual behavior
it cant able to remember pass and mail while click on remember me.

#### How to reproduce
* open the app 
* login with email and pass
* and click on remember me 
* then click on sing out and again try to login with the app 
* see that nothing remember mail and pass while click on remember me 

> Browser/App version: 4.0
 Operating system: Android **8.1.0** OPMI

#### Recording Of The Bug
https://youtu.be/PU48y3DA-Qg

**Comment by YahiaAngelo** [comment]
The point of "Sign out" is to forget your sign in info,
It's not a bug.
Thanks for reporting
