### ISSUE TITLE
More app description, privacy policy, etc.

### ISSUE THREAD

**Issue by HarryHeights** [YahiaAngelo/Karma#5]
Hi, I'm Harry. I recently stumbled on your app and installed it. However, there's no adequate information about the app. On the readme, it says social app. But, I don't know how to go about getting social on the app. It would be great if there was a very descriptive 'About' document. Aside from that, I'd love to know if there's a privacy policy. I mean parting away with my e-mail address ain't a small deal these days. 
If you don't have the time to create those documents (About, Privacy policy. In the event that you don't have them), I could help create them for you. If you supply me with tangible information(especially 'About' the concept of the app).
Thanks very much. I'd love to know your thoughts.

**Comment by YahiaAngelo** [comment]
Hi Harry,
Thanks for your report.
And the thing is this app is still beta (maybe even in early stage),
and the core idea of it is going above the limits with Firebase in an app that can you do a lot of things in it.
And of course i would appreciate your help if you edited anything and made a Pull request of it.
Thanks is advance.

**Comment by HarryHeights** [comment]
Alright. I'll send PRs for the privacy policy statement and contributor's guidelines. For the 'About' I'll wait till there's substantial detail of the app.
